[build]
  command = "npm run build:ssr"
  publish = "dist/photo-gallary/browser"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"
